name: CI - build and test

on:                                
    push:
      branches: [ main ]

jobs:
    build:                           

      runs-on: ubuntu-latest         

      steps:    
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: '11'
            distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        working-directory: ./
        timeout-minutes: 20
        run: ./gradlew build
        
      - name: deployReports or Update Website
        working-directory: ./
        timeout-minutes: 20
        run: |
          eval $(ssh-agent -s -t 600)
          ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")
          git config --global user.email "jwhee010@odu.edu"
          git config --global user.name "Project Actions"
          ./gradlew deployReports 
        